### ISSUE TITLE
Address validation schema

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#111]

**Comment by saheersk** [comment]
May I know what all validation do want can you brief it?

**Comment by dpgraham4401** [comment]
Hey @saheersk, apologies for the slow response. 

Happy you're interested in contributing, I'm part way through working on this one, sorry I haven't been keeping up the issue board while i'm on detail. I may just push what I've got and if you see improvement, you're welcome to submit something.

I can also go through and add a couple issues that may be more first time contributor friendly (with a better description ha). You can ping me on any of those issue and i can send it your way.

With regard to Address validation, we have a JSON schema for reference from the [e-Manifest GitHub repo](https://github.com/USEPA/e-manifest/blob/master/Services-Information/Schema/emanifest.json#L892). The hazardous waste manifest has a [Site Address](https://github.com/USEPA/e-manifest/blob/master/Services-Information/Schema/emanifest.json#L892) and [Mailing Address](https://github.com/USEPA/e-manifest/blob/b99add464d12e8682610713f31d4b698e44a7017/Services-Information/Schema/emanifest.json#L699) each has the meet the requirements when submitting. Meeting those covers about 90% of what needs to be done (not just for the Address but most of the rest of the Manifest model). Outside of that, if you think of other validations that can be applied to addresses, we have to be careful because we'll be pulling down manifests from the e-Manifest API that uses these validations as well and the data quality is not the best.

I have Manifest TypeScript interface defined in the branch I've been holding on to for too long.
