### ISSUE TITLE
Error handle bad login request

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#134]
# 🐞 Bug Report

## end goal
When user is not found or error occurs at login, display the error (bonus points for looking good while doing it).

## description
There is still a lot of prototype code in the login function and redux user slice in general. right now, when a user attempts to login and uses bad credentials or the haztrak server cannot be reached, an error is displayed by redux in the console but that's it.

This the [login.rejected reducer function](https://github.com/USEPA/haztrak/blob/4df8038da3691e8e1ea4d9873a599656a4f00897/client/src/app/user.slice.ts#L106) needs to be updated from 
```javascript
state.error = action.payload.error; // <-- The payload object is undefined when the promise is rejected
```
to 
```typescript
state.error = action.error.message; // <-- a string
```

**Comment by nirajpdn** [comment]
@dpgraham4401 , Please assign this to me.
