### ISSUE TITLE
Refactor LayoutSidenav_nav

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#153]
# 🚀 Feature Request
Refactor the navigation in the side column to a react sub-component. For example right now the [Site](https://github.com/USEPA/haztrak/blob/73a7cd8b581744b79db8f16fbd2fd21dc231357e/client/src/components/Nav/Sidebar.tsx#L32) and the [Help](https://github.com/USEPA/haztrak/blob/73a7cd8b581744b79db8f16fbd2fd21dc231357e/client/src/components/Nav/Sidebar.tsx#L72) drop down navigation are almost identical except for the links and texts, changes in the appearance of one would not be shown in the other.

---
 
![screenshot_22-11-04-16:03](https://user-images.githubusercontent.com/43794491/200064764-a12237b3-97b4-4ace-a72e-8095e4e1dbf7.png)

**Comment by ayobamiseun** [comment]
can I work on this?  if I understand the question you require another styling for either the Help menu?

**Comment by dpgraham4401** [comment]
Hey @ayobamiseun, I'm glad you're interested in contributing. let me get back to you on November 7th, I need to check that we can accept contributions from outside the EPA without some sort of an agreement.

**Comment by ayobamiseun** [comment]
I just try to run the client on my local. I was asked for a password. or how am I supposed to run it so I can start working on it ASAP?

**Comment by dpgraham4401** [comment]
@ayobamiseun you're one of the first outside our office looking to contribute, thanks in advance for your patience while we iron out the kinks. I'm realizing now there's not a good way to run the client without also running the server.

I'm open to suggestions if you have a ideas on ways we could improve this. This short conversation has already made me realize I need a better way to allow new contributors to get up and running more smoothly. 

The easiest way to get up and running is with a dockerized back end.
If you can follow these below commands, from the project root, they should get you up and running.

1. `$ cp server/.env.example server/.env && cp client/.env.example client/.env`
2. comment out the Database configs in [server/.env](https://github.com/USEPA/haztrak/blob/9d6f9b4917df2b1c2a1212193a23f7346b401ce2/server/.env.example#L25)
```
### Database Configs
# HT_DB_ENGINE=django.db.backends.postgresql_psycopg2
# default: django.db.backends.sqlite3

# HT_DB_NAME=my_database_name
# HT_DB_USER=database_username
# HT_DB_PASSWORD=MyP@ssw0rd
# HT_DB_HOST=192.168.1.116
# HT_DB_PORT=5432
```
3. You will need python on your system as well to use the runhaz.sh shell script
    ```$ ./runhaz -m && ./runhaz -l```
4. bring up the back end services with docker compose
```$ docker-compose up server redis celery```
5. start the client, 
6. you should be able to login with the below credentials which where loaded into the db.sqlite3 database with the runhaz.sh shell script commands. 
    * username: "testuser1"
    * password: "password1"

**Comment by dpgraham4401** [comment]
I wonder if it would just be easier to include the db.sqlite3 database for development purposes. If we did that, then that long list of commands (which I'm realizing may still throw errors since it doesn't mention the virtual environment) would be reduced significantly. 

I will need to return to this tomorrow. 

Again, thanks for your patience @ayobamiseun

**Comment by ayobamiseun** [comment]
@dpgraham4401  It will be better if we can set up the sqlite3 just for development purposes or develop the client side independently cos I am not comfortable working with python 😃

**Comment by dpgraham4401** [comment]
> @dpgraham4401 It will be better if we can set up the sqlite3 just for development purposes or develop the client side independently cos I am not comfortable working with python 😃

I agree, it would be great to have a way to work on parts of the react app that don't depend on the back end independently. 

I'll do some research, I suspect we doing something with docker will be the best option.

**Comment by dpgraham4401** [comment]
@ayobamiseun  I've mainlined docker-compose.dev.yaml and [updated the docs on how to use it](https://github.com/USEPA/haztrak/blob/main/docs/README.md#docker-compose). I need to go through and wordsmith the documentation but let me know if you have any problems.

**Comment by ayobamiseun** [comment]
I am sorry I have not reverted back to you, I have been trying to deploy the project on my local machine I feel I will just have to learn docker At this point.

**Comment by dpgraham4401** [comment]
@ayobamiseun, no problem. Let me know if you'd like to take another crack at this. 

If you find the documentation lacking in that area or you're experiencing an error you think could be fixed by us, please open an issue.

**Comment by ayobamiseun** [comment]
`docker-compose --env-file configs/.env.dev -f docker-compose.yaml -f docker-compose.dev.yaml up --build `
can you like explain what I am using the docker composer for I already have docker installed on my machine.

**Comment by dpgraham4401** [comment]
I apologize in advance if this over explains things, I'm never sure where to start, it's a real problem of mine.

docker-compose if just a way to simplify the process of starting up an application that depends on multiple containerized 'components'. Otherwise, you'd have to do something like open up four different terminals, one for each component, the start each container with a long list of flags. You could do the same thing with bash scripts but that gets kinda messy. 

To quote the [docker-compose overview](https://docs.docker.com/compose/)
> compose is a tool for defining and running multi-container Docker applications.

So, to oversimplify, our docker-compose does a couple things...
1. builds or pulls docker images for the parts of haztrak (redis, celery, the django RESTful API, and the react front end). So you don't even need python or node.js installed on your computer to run these, docker 'packages' everything that's needed to run haztrak in these containers.
2. starts the containers and feeds environment variables from the specified `--env-file`
3. The .dev.yaml file overrides values in the docker-compose.yaml specific to creating a local development environment (i.e., hot reloading so we don't have to restart the containers every time we make a change). The regular docker-compose.yaml file setups something closer to production environment.

Did you read the [documentation on this](https://github.com/USEPA/haztrak/blob/main/docs/README.md#deploying-haztrak) and, if so, is there something we can add to clarify things?

**Comment by ayobamiseun** [comment]
> ERROR: The Compose file './docker-compose.yaml' is invalid because:
> services.client.environment.CHOKIDAR_USEPOLLING contains true, which is an invalid type, it should be a string, number, or a null

I got the above error when I tried to run docker-compose up

**Comment by dpgraham4401** [comment]
@ayobamiseun are you still intersted in working on this? should I assign you again?

**Comment by ayobamiseun** [comment]
I am thinking of deleting my old fork cause it has a lot of unmerged changes, what do feel I should do that won't have anything to do with the old changes?

**Comment by dpgraham4401** [comment]
@ayobamiseun sorry just saw this comment, must have slipped through. Just pull the unmerged changes before submitted the PR.
