### ISSUE TITLE
'Add Transporter' section to New Manifest

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#154]
# 🚀 Feature Request

This is a high level issue that covers the sub-issues that will be needed to implement a React component used for searching the haztrak http server for existing transporters and adding the transporter to a manifest being edited. 

Depends on
- [x] #158 
- [x] #159 
- [x] #177
- [x] #178

**Comment by nirajpdn** [comment]
I want to work on this. Could you assign this to me ?

**Comment by dpgraham4401** [comment]
Hey @nirajpdn, I'm glad you're interested in contributing. let me get back to you on November 7th, I need to check that we can accept contributions from outside the EPA without some sort of agreement.

**Comment by nirajpdn** [comment]
@dpgraham4401, do i need to setup server as well in my local environment  ?
If server is hosted for development & testing, then please provide me api url. 
And development login credentials.

**Comment by dpgraham4401** [comment]
Hey @nirajpdn, apologies for the delay. 

Since we don't currently have a dedicated server for development and testing, I'm adressing this issue by adding a way to setup a local development environment with docker-compose. The changes are in this [branch here](https://github.com/dpgraham4401/haztrak/tree/more_cleanup). At the moment It works, but I would say it's incomplete and not documented or fully tested. When it's complete, we should be able to bring up the entire development environment with one command, `$ docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up` and you'll be able to work on the React client. 

Again, currenty it works, but It requires checking in the sqlite3 database file into vcs which I would like to avoid. If I have time, I'll get to this today.

**Comment by nirajpdn** [comment]
@dpgraham4401  No problem. I will check it out. Thanks.

**Comment by dpgraham4401** [comment]
I've mainlined docker-compose.dev.yaml and [updated the docs on how to use it](https://github.com/USEPA/haztrak/blob/main/docs/README.md#docker-compose). I need to go through and wordsmith but let me know if you have any problems.

**Comment by nirajpdn** [comment]
> @nirajpdn I've mainlined docker-compose.dev.yaml and [updated the docs on how to use it](https://github.com/USEPA/haztrak/blob/main/docs/README.md#docker-compose). I need to go through and wordsmith but let me know if you have any problems.

Thank you @dpgraham4401. I have successfully setup project locally. I have created superuser and testing endpoints.  I will work on above issue.

<img width="1406" alt="Screen Shot 2022-11-08 at 21 06 37" src="https://user-images.githubusercontent.com/59108522/200604345-3686ecc6-0597-41f4-af44-1712b161a24b.png">

**Comment by dpgraham4401** [comment]
Before you get started, here some additional context. I know you're only worried about the react component but this may help clarify.

All transporters have to have a unique [EPA ID number](https://github.com/USEPA/haztrak/blob/4df8038da3691e8e1ea4d9873a599656a4f00897/client/src/types/Handler/Handler.ts#L5) called epaSiteId in our type definition. 

For now, the form can just include a field for the EPA ID number. We may want to add the transporter name to the search criteria later but I think it's best to keep this issue simple at first.

To make things more complicated, in the future, we will need to add another form (or extend this one) to allows users to search for transporters via third party services (RCRAInfo). You don't need to worry about this, and if that doesn't make perfect sense than don't worry about it.

@nirajpdn let me know if you have any questions, and thanks for your assistance! 🥇

**Comment by dpgraham4401** [comment]
> Can i create new route for transporter search ?

This is embarrassing, I remember I started this but realized it was [not what we needed](https://github.com/USEPA/haztrak/blob/4df8038da3691e8e1ea4d9873a599656a4f00897/client/src/components/ManifestForm/ManifestForm/ManifestForm.tsx#L49). The Transporter search form will be on the same page as the manifest form. It's URL is /manifest/{mtn}/edit. However instead of showing all the transporter fields like there is in there now, it's just the EPA ID number. 
![Screenshot from 2022-11-08 21-37-13](https://user-images.githubusercontent.com/43794491/200723976-7ebb702e-bf3c-439c-b8f2-83f0da71c130.png)

> So , the form has only one field epaSiteId and based on this we have to search transporter , right ?

Correct, let's keep it simple for now


> I haven't seen any api endpoints name related to transporter.

We don't have an API endpoint yet for transporter yet, I can prioritize that though. you can plan on it's endpoint being `/api/trak/transporter/{epa_id}`.

>  Is handler a transporter ?

Almost, the transporter extends the Handler model and adds 2 fields. order (int), and manifest (foreign key). We don't have a Type interface defined [in the types directory](https://github.com/USEPA/haztrak/tree/main/client/src/types) unfortunately. You can use the Handler interface if for the time being.

**Comment by dpgraham4401** [comment]
This is a relatively large and issue, this thread has inspired me to write smaller more focused issues. Let me know if you'd be interested in another issue.

**Comment by nirajpdn** [comment]
> This is a relatively large and issue, this thread has inspired me to write smaller more focused issues. Let me know if you'd be interested in another issue.

Sure @dpgraham4401, which issue i need to work for now ? You can assign me in any issue of frontend for now. It is taking me a bit time to understand the project 😀.

**Comment by nirajpdn** [comment]
> @nirajpdn check out #134, #157 and #123. All three are relatively small issues, should be easy fixes.
> Sure @dpgraham4401 , i will be working on these issues.
> If you ahven't already figured out, there's a lot of things to do, so if you see something you'd like to work on besides what's listed in the project's issues currently, don't be afraid to open up an issue let me know what you'd like to work on. The Sky's the limit.
> I have got basic idea about the project and i will exploring more about it by doing.
