### ISSUE TITLE
Add haztrak 'logo' to login screen

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#157]
# 🚀 Feature Request

haztrak does not really have a logo, but for now, it would be good to add a label to the login screen.

We can dimply use the same 'logo' that's in the top left corner of the home screen (after login) [found here](https://github.com/USEPA/haztrak/blob/c6cfe1cb5f0940184ba3d69dcbfcc04fd8a1ec5c/client/src/components/Nav/TopNav.tsx#L23)

**Comment by nirajpdn** [comment]
@dpgraham4401, assign this to me.

**Comment by dpgraham4401** [comment]
closd with #158
