### ISSUE TITLE
Create TypeScript Interface for the Transporter model.

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#158]
# 🚀 Feature Request

Add a new file, or add to [Handler.ts](https://github.com/USEPA/haztrak/blob/main/client/src/types/Handler/Handler.ts), with the `Transporter` model TypeScript interface definition in the [/client/src/types](https://github.com/USEPA/haztrak/tree/main/client/src/types) directory. 

## context 

The Transporter extends the [`Handler`](https://github.com/USEPA/haztrak/blob/main/client/src/types/Handler/Handler.ts) model with two fields, order (integer) and manifest (integer, also a foreign key to Manifest model). The model definition for transporters on the server can be found at [/server/apps/trak/models/transporter.py](https://github.com/USEPA/haztrak/blob/main/server/apps/trak/models/transporter.py).

**Comment by nirajpdn** [comment]
@dpgraham4401 , assign this to me.

**Comment by nirajpdn** [comment]
# 🚀 Feature Request
 Add a new file, or add to [Handler.ts](https://github.com/USEPA/haztrak/blob/main/client/src/types/Handler/Handler.ts), with the `Transporter` model TypeScript interface definition in the [/client/src/types](https://github.com/USEPA/haztrak/tree/main/client/src/types) directory.
## context
> The Transporter extends the [`Handler`](https://github.com/USEPA/haztrak/blob/main/client/src/types/Handler/Handler.ts) model with two fields, order (integer) and manifest (integer, also a foreign key to Manifest model). The model definition 
for transporters on the server can be found at [/server/apps/trak/models/transporter.py]. 
(https://github.com/USEPA/haztrak/blob/main/server/apps/trak/models/transporter.py).

Does manifest contain a populated object or just manifest_id (i.e foreign key) ?

**Comment by dpgraham4401** [comment]
> Does manifest contain a populated object or just manifest_id (i.e foreign key) ?

the manifest field just contains a foreign key, not a complete manifest object.

**Comment by dpgraham4401** [comment]
closed with #163
