### ISSUE TITLE
docker-composer up error 

### ISSUE THREAD

**Issue by ayobamiseun** [USEPA/haztrak#164]
# 🐞 Bug Report

> ERROR: The Compose file './docker-compose.yaml' is invalid because:
> services.client.environment.CHOKIDAR_USEPOLLING contains true, which is an invalid type, it should be a string, number, or a null

I got the above error when I tried to run docker-compose up and I already copy my .env for both my client and server.

**Comment by dpgraham4401** [comment]
I believe your git repo is based on an older commit, Can you pull the latest commits and retry the command listed in the [docker-compose docs](https://github.com/USEPA/haztrak/tree/main/docs#docker-compose). You shouldn't have `CHOKIDAR_USEPOLLING` anywhere in your project file.

> I already copy my .env for both my client and server.

Copying .env files is only necessary if you're going to use a local installation of python/node.js. The environment variables are passed in an environment file denoted via the `--env-file` flag.

**Comment by dpgraham4401** [comment]
@ayobamiseun let me know if the problem persist after you pull the most recent upstream changes.

**Comment by ayobamiseun** [comment]
I was finally able to deploy it by deploying individual containers. I tried using docker-compose but it was getting stuck on trying to install npm.
