### ISSUE TITLE
migration error 

### ISSUE THREAD

**Issue by ayobamiseun** [USEPA/haztrak#166]
# 🐞 Bug Report

`WARNINGS:
?: (staticfiles.W004) The directory '/Users/Ayobamiseun/haztrak/server/static' in the STATICFILES_DIRS setting does not exist.`

`
RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': connection to server at "192.168.1.116", port 5432 failed: Operation timed out
        Is the server running on that host and accepting TCP/IP connections?
`
I got the above while running migration.

**Comment by dpgraham4401** [comment]
It's your database configs. It's trying to connect to a database that you haven't set up. See our [Configuration documentation](https://github.com/USEPA/haztrak/blob/main/docs/Configuration.md).
