### ISSUE TITLE
Edit current manifest (react-hook-form Value props)

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#248]
# 🚀 Feature Request

Make use of react-hook-form's Value to set values in the Manifest form. This is going to touch a lot of different `ManifestForm` sub components and will require prop drilling the default values.

Open to suggestions, possibility of using a context provider, or see if react-hook-form has something for this. ***Further Research is required***

sub-tasks

- [x] #279
- [ ] accept manifest(mtn or manifest?) as prop to Manifest Form

**Comment by waqas-cs** [comment]
Hey there, I would like to work on this issue!

**Comment by dpgraham4401** [comment]
@waqas-cs, heads up, this is a relatively involved issue.

We don't even have fixture data that's loaded into the database on start up to really work on this (at the moment).

I'm happy to assign you this on GitHub, but I don't recommend trying wrap this up in the same PR as #301

**Comment by dpgraham4401** [comment]
looking at closing this issue, see #335 

@waqas-cs I never heard back from you, I assume you're not working on this?

**Comment by dpgraham4401** [comment]
This issue is now irrelevant.
