### ISSUE TITLE
Remove badge when notification count is zero

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#255]
# 🐞 Bug Report

This should be an easy one. when the count of notifications is zero, don't show a red badge in the notification button. 

![image](https://user-images.githubusercontent.com/43794491/210084943-45efcd24-f4ad-4021-8f72-7cfaa197f0bc.png)

**Comment by Badrri-Narayanan** [comment]
Hi, can you please assign this to my name?

**Comment by dpgraham4401** [comment]
@Badrri-Narayanan you got it!

let me know if you need help getting up and running, the [deployment documentation](https://github.com/USEPA/haztrak/blob/main/docs/Deployment.md#docker-compose) is slightly out of date (i'll fix that now).

The easiest way is to use the docker-compose command
```shell
$ docker-compose --env-file configs/.env.dev up --build
```

**Comment by dpgraham4401** [comment]
@Badrri-Narayanan give me 5 minutes and I'll get on this

**Comment by dpgraham4401** [comment]
@Badrri-Narayanan I've updated the docs on [setting up the client locally](https://github.com/USEPA/haztrak/blob/main/docs/Deployment.md#deploying-the-react-client-locally). There's 2 environment variables to set

After that, the mock service worker should be initiated when `REACT_APP_HT_ENV` environment variable is set to `TEST` in the, and you should be able to log in with username `testuser1` and password `password1`

**Comment by dpgraham4401** [comment]
I'm going to look into why the docker-compose file is not working, I have a theory.

**Comment by dpgraham4401** [comment]
@Badrri-Narayanan thank you so much for finding this issue with the docker-compose, I've found the problem and will be fixing this today.
