### ISSUE TITLE
Unable to start the Client container using docker-compose command

### ISSUE THREAD

**Issue by Badrri-Narayanan** [USEPA/haztrak#259]
# 🐞 Bug Report

When I used the following command to start the application, I am getting the error mentioned below,

`docker-compose --env-file configs/.env.dev up --build`

#### Error message:

![image](https://user-images.githubusercontent.com/26011119/210129546-a812d7f6-156d-47ed-86fb-e8f739ff3632.png)

**Comment by dpgraham4401** [comment]
It looks like it was, in part, due to the [validation introduced by NPM](https://github.com/npm/cli/issues/5113) also discussed [here](https://github.com/npm/cli/issues/5125) and we're just seeing it.
