### ISSUE TITLE
Update Docker Node image from 16 to 18

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#285]
# 🐞 Bug Report

In the Dockerfile (builder sections) and docker-compose.yaml, convert the Node:16 image usage to Node:18. 

May require nothing other than a couple line changes, But it would be good to do some thorough testing before finalizing the PR and looking at the change log.

**Comment by Niravprajapati1** [comment]
Can i work on this ?

**Comment by dpgraham4401** [comment]
@Niravprajapati1, it's all yours!
