### ISSUE TITLE
Unable to retrieve the list of sites for Admin view

### ISSUE THREAD

**Issue by Badrri-Narayanan** [USEPA/haztrak#287]
# 🐞 Bug Report

I don't know if it is covered as a part of existing issues if so kindly close this issue.
For **admin** user, upon visiting the sites page, the spinner keeps on loading

![image](https://user-images.githubusercontent.com/26011119/210583256-e6a2aab2-250e-4a75-98d6-7201c9de304a.png)

Upon further inspection, we are getting the following stack trace in the backend
```
server            | [04/Jan/2023 09:45:44] "GET /api/trak/site/ HTTP/1.1" 500 16016
server            | Internal Server Error: /api/trak/site/
server            | Traceback (most recent call last):
server            |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
server            |     response = get_response(request)
server            |   File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
server            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
server            |   File "/opt/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
server            |     return view_func(*args, **kwargs)
server            |   File "/opt/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
server            |     return self.dispatch(request, *args, **kwargs)
server            |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
server            |     response = self.handle_exception(exc)
server            |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
server            |     self.raise_uncaught_exception(exc)
server            |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
server            |     raise exc
server            |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
server            |     response = handler(request, *args, **kwargs)
server            |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 199, in get
server            |     return self.list(request, *args, **kwargs)
server            |   File "/opt/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 38, in list
server            |     queryset = self.filter_queryset(self.get_queryset())
server            |   File "/app/apps/trak/views/sites.py", line 28, in get_queryset
server            |     return RcraProfile.objects.get(user=user).epa_sites.all()
server            |   File "/opt/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
server            |     return getattr(self.get_queryset(), name)(*args, **kwargs)
server            |   File "/opt/venv/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
server            |     raise self.model.DoesNotExist(
server            | apps.trak.models.rcra_profile.RcraProfile.DoesNotExist: RcraProfile matching query does not exist.
```
We need to find out why the backend is failing. Also, we need to let the front-end know that something went wrong and we need to display an appropriate error message to the user.

**Comment by dpgraham4401** [comment]
Thanks for the issue!

similar to what I was talking about in #204, Our fixture data currently only includes 3 instances. 

1. a User instance for testuser1
2. a User instance for admin
3. a RcraProfile for testuser1

The User modal is responsible authentication (why we can login with both testuser1 and admin) but RcraProfile is responsible for access to sites, site permissions, and other things related to interfacing with the RCRAInfo Restful APIs.

With that being said, you're right. The server should handle this gracefully. 

Without looking, I bet the server is responding with a 500 code which we could also handle better on the front end by displaying an error. Would you like to take a look into that?

BTW I appreciate your contributions so far, it's given me a chance to focus on the server which has been neglected recently :)

**Comment by Badrri-Narayanan** [comment]
@dpgraham4401 , sure I can take up adding sad path validation in frontend and displaying an error modal saying "something went wrong. Please try again after sometime" to the user. Will that be fine?

Also, can we inject some sample data into our postgres DB during docker-compose startup? Kindly let me know your thoughts.

**Comment by dpgraham4401** [comment]
Note fro #281 : example reason why it would be great to add back some fixtures that are loaded on start for new developers. The new developer was unable to, intuitively, reach the manifest related functionality because there are no sites loaded. 

ToDO: add one of the preprod testing sites as a fixture.
