### ISSUE TITLE
e-Manifest terminology 101

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#290]
# 🚀 Feature Request

Add a page (maybe called "Terminology"?) to the [documentation](https://usepa.github.io/haztrak) that explains the terminology used by RCRAInfo and e-Manifest (e.g., generator, transporter, tsdf, uniform hazardous waste manifest, waste codes) so new Haztrak contributors have a basic understanding of what each term means and how it's related to models/components in Haztrak's implementation.

The hardest part of these term definitions will be knowing where to stop, also not reinventing the wheel. Just enough information to point contributors/developers in the right direction).

It shouldn't go into legal definitions of what each thing is. Instead, when applicable...
1. Give a one-sentence overview (e.g., A Generator is an instance of a handler that ... )
2. How a term is related to other terms (e.g., A generator uses manifests to ... )
    - How Haztrak differs from RCRAInfo (e.g., our "Site" is not the same as a RCRAInfo "Site"). 
3. A link to where they can find more background information on epa.gov, e-CFR, or other epa sites (for those interested)

The PR to close this issue doesn't need to cover everything. but I good starting point/outline (even if just left with ToDo items in the documentation) would be great!

EDIT:
A page can be added to our docs by just adding a markdown page in the [docs/haztrak_book/src](https://github.com/USEPA/haztrak/tree/main/docs/haztrak_book/src) directory, adding a link to that file in [docs/haztrak_book/src/SUMMARY.md](https://github.com/USEPA/haztrak/blob/main/docs/haztrak_book/src/SUMMARY.md). The GH pages will be updated via GH actions workflow.

**Comment by dpgraham4401** [comment]
@wiljnichepa interested? no pressure lol

**Comment by wiljnichepa** [comment]
@dpgraham4401 yeah, I'll take this. sounds fun. you don't truly know something unless you can teach it!
