### ISSUE TITLE
Notification badge alignment

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#301]
# 🐞 Bug Report

The button (envelope icon) that acts as the notification dropdown moves to the left when the first notification is set. The item alignment/justification needs to be fixed (likely needs to wrapped in a div or another html tag) so when the first notification is set, the button i not moved to the left. 

<img width="140" alt="image" src="https://user-images.githubusercontent.com/43794491/211202188-26ec306d-1b53-44a6-bcd0-72105ec7cb68.png">

<img width="140" alt="image" src="https://user-images.githubusercontent.com/43794491/211202254-6d2d1955-4feb-4ae0-bfb0-6cb2eef952f4.png">

This is a cosmetic fix only, the functionality is not experiencing any issues currently.

**Comment by waqas-cs** [comment]
Hey there, I would like to work on this issue!

**Comment by dpgraham4401** [comment]
@waqas-cs, you got it!

Let me know if you need anything
