### ISSUE TITLE
Replace FontAwesome Script tag with react-fontawesome

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#311]
# 🚀 Feature Request

Get to a point where all font awesome usage goes thru the FontAwesome react component. It's a little easier (cleaner) when using things like animations. The PR should also remove the script tag in index.html.

see Font Awesome documentation here https://fontawesome.com/docs/web/use-with/react/

**Comment by lokeshvasnik** [comment]
Let me try

**Comment by dpgraham4401** [comment]
You got it, I'm out of the office and can't login to assign you but it's all yours :)David GrahamOn Jan 13, 2023, at 2:09 AM, Lokesh Vasnik ***@***.***> wrote:﻿
Let me try

**Comment by dpgraham4401** [comment]
It's worth noting that we don't NEED to do this, we could just continue to include the entire FontAwesome library via the <script> tag. 

As I understand it, if we use the FontAwesome Icon component, it's good for performance (since we don't need to load the entire library), it also allows us a better way to programmatically control those icons and their appearance. However, it's more complex, there's more LOC involved, it's also another dependency*

*Maybe better as an explicit dependency in our package.json than an implicit dependency that just hangs out in our index.html.
