### ISSUE TITLE
Automate dependency review

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#353]
# 🚀 Feature Request

Add a workflow that verifies that new dependencies have licenses that are compatible with Haztrak's license. 

Under the USEPA GitHub org, we are allowed to use actions from [actions/*](https://github.com/actions), which has [dependency-review-action](https://github.com/marketplace/actions/dependency-review).

The new workflow should only run when the dependency requirement files changes (package-lock.json and requirements.txt)

**Comment by nihonjinrxs** [comment]
Happy to put together an Actions workflow to handle this one. OK if this is an independent workflow, or should I be including it as a step in another workflow?

**Comment by nihonjinrxs** [comment]
Also, is there a specific list of licenses the EPA or US Gov has deemed compatible with the MIT license used on this project, or should I be using [the default of the action (any SPDX-compliant identifiers)](https://github.com/marketplace/actions/dependency-review#configuration-options), or my best guess at "permissive" open source licenses like MIT?

**Comment by nihonjinrxs** [comment]
Finally, what minimum level of security vulnerability (`low`, `moderate`, `high`, `critical`) should cause the PR check to fail?
