### ISSUE TITLE
View Site Manifest Button

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#379]
# 🚀 Feature Request

Pretty simple, add a new button to navigate from `/site/<siteId>` to `/site/<siteId>/manifest`.

![image](https://user-images.githubusercontent.com/43794491/224047520-330ae3e1-46bf-481f-a159-130bb7bdd5f2.png)

Use of Font Awesome Icon's component ( `<FontAwesomeIcon/>`) welcome.

**Comment by gorostiaga** [comment]
May I take this issue?
I've sent a PR already :grinning:
