### ISSUE TITLE
RejectionInfo model

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#385]
# 🚀 Feature Request

Implement the necessary entity definition and assimilate the new object into the existing ORM database schema.

This PR does not need to include a serializer.
see #386 

See the [Emanifest schema](https://github.com/USEPA/e-manifest/blob/master/Services-Information/Schema/emanifest.json) for the definition of `RejectionInfo` and the corresponding field.

**Comment by dpgraham4401** [comment]
@tishiljk3 Would you like to be assigned?

**Comment by tishiljk3** [comment]
@dpgraham4401 Of course, but I do have some concerns. I have begun working on this problem; while running server tests, I discovered a problem with the array field. The postgres database is running OK in my local environment, I believe that the issues in this case are being caused by the fact that sqlite databases do not support array fields. Do we test with sqlite here?

**Comment by dpgraham4401** [comment]
@tishiljk3 We use a postgres service on the github actions to test the server
https://github.com/USEPA/haztrak/actions/runs/5277594811/workflow

However, I do see this error in the logs https://github.com/USEPA/haztrak/actions/runs/5277594811/jobs/9545840032#step:6:8964

If the server is not configured to run against a postgres db it will fall back to sqlite. I've left that fallback in as a way to make testing easier for newcomers. So far it hasn't been a problem since we haven't used anything that has deviated from the the SQL standard. It looks like it's not configured correctly and it may be falling back to sqlite. 

Thanks for catching that, we'll need to fix it so our test run against postgres.

## Use Postgres specific features
I'm open to making the commitment to postgres, especially if it provides us tangible benefits. But, it may serve us better to continue using non-postgres specific SQL features for the time being. For the array of MTN we can just use a TextField. Is there a benefit to using an arrayfield that we'd be gaining right now?

**Comment by dpgraham4401** [comment]
@tishiljk3 For what it's worth, there are issues that are probably higher priority, easier, and more interesting than this one if it keep giving you trouble. Just say that word and I'd be happy to assign.

**Comment by tishiljk3** [comment]
@dpgraham4401 Thank you for the improvements; there is no issue with rejection info model now. I will soon raise PR for that.
