### ISSUE TITLE
Filter MTN by Status

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#401]
# 🚀 Feature Request

Using the existing [MtnTable component](https://github.com/USEPA/haztrak/tree/main/client/src/components/MtnTable) we need to add a way to filter the viewable manifest tracking numbers (MTN) by their status. 

How this is to implemented in the UI layer is up for grabs, TBD. 

![image](https://user-images.githubusercontent.com/43794491/225110291-c2aa1107-63e9-4196-b344-3683d0475a16.png)

**Comment by ayobamiseun** [comment]
hi @dpgraham4401, I am fully back now. this is will be a good issue to pick.

**Comment by dpgraham4401** [comment]
@ayobamiseun it's all yours. 

You'll probably want some dummy manifest data, you can create some draft manifest objects through the Django admin interface which should be accessible on port :8000 of the same as the front end http://localhost:8000. The test admin credentials can be found in the [local development docs](https://usepa.github.io/haztrak/development/local-development.html#fixtures)

**Comment by ayobamiseun** [comment]
can you point to documentation of how to load the project on my local?

**Comment by dpgraham4401** [comment]
setting up a local development environment? yeah, it's at https://usepa.github.io/haztrak/development/local-development.html

Right now we use docker (and docker compose) to spin up all the necessary services.

**Comment by dpgraham4401** [comment]
@ayobamiseun If it help, you might consider adding [React table v8](https://www.npmjs.com/package/@tanstack/react-table) as a dependency.
