### ISSUE TITLE
Configure API versioning thru DRF

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#409]
~~Currently we just have a `/v1/` stuck in our url configuration.~~ Lets follow the [DRF versioning documentation](https://www.django-rest-framework.org/api-guide/versioning) so we can actually make use of this information and version our APIs as `/api/v1/<otherParameters>`

Follow the documentation for [URL path versioning](https://www.django-rest-framework.org/api-guide/versioning/#urlpathversioning) or [Namespace versioning](https://www.django-rest-framework.org/api-guide/versioning/#namespaceversioning). Either should work for this project.

**Comment by SaranshBaniyal** [comment]
I would like to work on this @dpgraham4401, can you please assign this issue to me

**Comment by dpgraham4401** [comment]
@SaranshBaniyal you got it! 

I don't wat to scare you but there's a couple things you'll want to be aware of before starting this issue. 

1. I realized after I made this issue that we actually do not version our API. Sorry about that, not sure what I was thinking. Not a problem, we/I just need to make some adjustments to the react client after. 
    - lets add the version URL parameter after `/api/`. So `/api/trak/manifest` would become `/api/v1/trak/manifest`.
3. When you add the url version parameter, I suspect a large number of tests will fail in the `/server/apps/trak/tests/views/` directory since there are test in there that use details of the URL.

Feel to open a draft PR or let me know if you have any questions.

Cheers!

**Comment by SaranshBaniyal** [comment]
Thanks for assigning the issue, I am not sure how to deal with the second point regarding the tests as of now, but I will try to resolve it, or ask my doubts here.

**Comment by SaranshBaniyal** [comment]
Hey @dpgraham4401 can you help me out, is there some separate code for v1 and v2 in the code base or should I just make all of it v1 for now?

**Comment by dpgraham4401** [comment]
All the `/api/` endpoints are `v1` for now. 

@SaranshBaniyal heads up, I finally got around to separating the `trak` django app into two separate apps, so now there's a `sites` django app in addition to the `trak` app. Both of those Django apps should have `v1` as there default version.

**Comment by SaranshBaniyal** [comment]
Thanks @dpgraham4401 that was very helpful, I will try to resolve the issue as soon as possible (please excuse the delay, I'm a beginner to django)
