### ISSUE TITLE
Add mdbook git repo configs 

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#465]
# 🚀 Feature Request

[mdbook](https://github.com/rust-lang/mdBook) allows us to add two icons to the top right of the documentation...
1. a link to the Git  URL
2. a link to edit the specific page you're on on github (maybe other Git hosting services as well, haven't' tried, doesn't matter for this PR).

see documentation here https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options

**Comment by dpgraham4401** [comment]
@scottdchristian interested?

**Comment by scottdchristian** [comment]
Thanks will take a peek after the Wednesday release.

**Comment by hamzaaslam2121** [comment]
Can I have a go at this by any chance?

**Comment by dpgraham4401** [comment]
Hey @hamzaaslam2121, 

Absoluetly, It's all yours.

Heads up @scottdchristian.

**Comment by scottdchristian** [comment]
Thanks, it's been on my to do list, but please go for it @hamzaaslam2121
