### ISSUE TITLE
Refactor WasteLineTable display

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#622]
# :rocket: Feature Request

We recently refactored the table of transporters to a list of cards that use the [auto-animate library](https://github.com/formkit/auto-animate) for UI improvement. We should  do something similar with waste line information (just below). The new transporters list looks like the following.  

![image](https://github.com/USEPA/haztrak/assets/43794491/ce9bffb0-1986-483b-bec6-1a210658167f)

The Row Action items (move up, move down, remove) (see [Transporter Table equivalent here](https://github.com/USEPA/haztrak/tree/main/client/src/components/Manifest/Transporter)) were moved from 3 distinct (poorly formatted) buttons to a dropdown.

![image](https://github.com/USEPA/haztrak/assets/43794491/0b02e60f-32da-4233-a15c-f3dbb80548da)

The user can drill down for additional information by using the accordion to display more information, like below. This has the added benefit of only showing what the user needs initially, and more information can be added to the accordion when needed/desired. 

![image](https://github.com/USEPA/haztrak/assets/43794491/7de96a9c-83e1-4915-a2be-3ad805573a5c)

A PR that closes this issue will employ unit tests that show the feature is functioning as expected. The wasteline list should follow the below expected behavior. 

1. Display a card for each waste line on a manifest
2. each waste line renders a dropdown on the right with the available actions the user can take on a waste line
    -  edit
    - remove
3. each waste line renders a button (chevron/arrow) that collapses/expands the accordion. 
4. When expanded the card should display the below info
    - The federal waste codes
    - the generator state waste codes
    - the TSDF state waste codes
    - The container type
    - the quantity (number of containers)
    - The waste description
5. The list should use the auto-animate library to add transitions. (this will require that the key used for each item in the list will need to be independent of the order of the wasteline). 

for reference the current waste line table looks like the below

<img width="630" alt="image" src="https://github.com/USEPA/haztrak/assets/43794491/4694d278-fbd5-45e4-ad7a-3070c9165e96">

**Comment by ayobamiseun** [comment]
Let me work on this.
